Feat/35/landing page/iteration-1
SYNRGY-6-TEAM-5/frontend-web pull request #18
Opened 2024-01-08 17:04 UTC by Mwazowsky

Added:

- [ ] All components as per required in figma design

Need to do: 
- [ ] Search Form Need to be able to submit actual data

2024-01-09 01:41 UTC, bayuuat requested changes

2024-01-09 01:41 UTC, bayuuat commented on src/assets/svg/index.ts
> +export { default as Logo } from "./logo1.svg?react";
ini yang logo utama kita kayanya ada 3 wkwk, MainLogo, Vector sama Logo, minta tolong dijadiin 1 aja mas

2024-01-09 01:41 UTC, bayuuat commented on src/pages/home/components/containers/brandsBanner.tsx
> +    <div className={`md:h-18 flex h-24 w-full items-center justify-end bg-white px-6 md:px-9 lg:justify-between lg:px-20`}>
ditambahi padding/margin atas bawah lagi mas, jarak atas sekitar 50px jarak bawah sekitar 100px

2024-01-09 01:41 UTC, bayuuat commented on src/pages/home/index.tsx
>              {/* <Services /> */}
komen komen kalo ngga dipake dihapus aja mas

2024-01-09 01:41 UTC, bayuuat commented on src/pages/home/components/ui/SearchFilter.tsx
> +                <TabsContent
minta tolong per tab content dipisah bisa ngga mas? biar ngga bulk disini

2024-01-09 01:41 UTC, bayuuat commented on src/pages/home/components/ui/SearchFilter.tsx
> +                                      <DialogContent className="sm:max-w-[425px] backdrop-blur-md">
Dialog content jug bisa dibuat komponen sendiri aja.

2024-01-10 03:11 UTC, RutriAyut commented on src/pages/home/components/containers/CtaSection.tsx
> +              Signup Now
tolong diganti jadi "sign up"

2024-01-10 03:11 UTC, RutriAyut commented on src/pages/home/components/containers/HeroSection.tsx
> +            {HeroTexts.thirdText}
di figma text capital semua

2024-01-10 03:11 UTC, RutriAyut commented on src/pages/home/components/ui/SearchFilter.tsx
> +                                      <DialogTrigger asChild>
maaf untuk tombol ini mengarah ke modal untuk memilih penerbangan yang dari dan akan dituju <img width="177" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/87faedf7-e9ea-4109-a6b7-312957c14938">

2024-01-10 03:11 UTC, RutriAyut commented on src/pages/home/components/ui/SearchFilter.tsx
> +                              <Select
maaf, untuk tombol ini sepertinya digunakan untuk memilih class tiket yang dipesan
<img width="335" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/73c16a7a-5033-42e3-bbc8-be98749a070c">

2024-01-10 03:11 UTC, RutriAyut commented on src/pages/home/components/containers/OurServices.tsx
> +          <CardContent className="flex w-full flex-col gap-4 p-4">
mungkin bisa dibikin kayak yang di Tiket.tsx

2024-01-10 11:52 UTC, bayuuat commented
LGTM ✅

2024-01-10 11:52 UTC, bayuuat approved these changes

2024-01-10 11:59 UTC, RutriAyut approved these changes
Ok Thanks

2024-01-10 11:59 UTC, merged