Feat/71/register
SYNRGY-6-TEAM-5/frontend-web pull request #31
Opened 2024-01-22 02:46 UTC by ziyad1412

signup error tampil notif
signup success redirect ke page otp (belum bisa succes succes)

2024-01-22 13:31 UTC, bayuuat requested changes

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +  const role = Cookies.get("role");
token sama role bisa dihapus karena ngga kita pake

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +  }
statement if ini juga bisa dihapus aja

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +        emailAddress: email,
harusnya pake email bukan emailAddress jadinya `email: email,`

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +        if (res.status === 201) {
kalo lihat di swagger statusnya 200, tapi bisa dicoba dulu yaa

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +          Cookies.set("accesstoken", res.data.token);
yang diset ke Cookies res.data sama email dan password ya jadinya

```
Cookies.set(
   "otpData",
   JSON.stringify({ ...res.data, email: email, password: password }),
);
```

2024-01-22 13:31 UTC, bayuuat commented on src/pages/register/components/RegisterForm.tsx
> +        if (error.response) {
yang error error ini aku kurang yakin sih, kalo breaking bisa dihapus aja

2024-01-22 14:49 UTC, bayuuat approved these changes

2024-01-23 02:48 UTC, Mwazowsky approved these changes

2024-01-23 02:49 UTC, merged