feat: search ticket & integrate done
SYNRGY-6-TEAM-5/frontend-web pull request #36
Opened 2024-01-25 14:25 UTC by bayuuat

## CUMAN SAMPE SEARCH YA, FILTER & EDIT BELUM

Di merge dulu soalnya udh > 20 file edited

![image](https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/68576415/bebd7327-f2d4-47c5-9c53-934c151b4055)

![image](https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/68576415/3f2cdae3-4322-4248-99a5-8aef2412a146)

![image](https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/68576415/a1dc850b-2153-4e78-8863-82cd20393500)

2024-01-25 16:25 UTC, Mwazowsky requested changes
Udah oke untuk fitur search flight  ticket nya, cuman bug di search airport nya jadi ga jalan. coba cek lagi di bagian yang aku komen.

2024-01-25 16:25 UTC, Mwazowsky commented on src/pages/home/components/ui/form/OneWayForm.tsx
> +  const { airports, handleSearch, fetchAirports } = useHome();
params n setparams ini dihapus karena apa ya?, soale ini kalo gaada, fungsi search airport nya jadi ga jalan.

2024-01-25 16:41 UTC, bayuuat commented on src/pages/home/components/ui/form/OneWayForm.tsx
> +  const { airports, handleSearch, fetchAirports } = useHome();
eitss iya bener, sorry tadi lupa ga ngecek mau nambahin debounce wkwk
fixed ya

2024-01-26 02:18 UTC, Mwazowsky approved these changes

2024-01-26 03:25 UTC, RutriAyut approved these changes

2024-01-26 04:18 UTC, merged