Feat/74/add ons
SYNRGY-6-TEAM-5/frontend-web pull request #46
Opened 2024-02-01 15:34 UTC by anggaihza

2024-02-01 17:32 UTC, bayuuat requested changes

2024-02-01 17:32 UTC, bayuuat commented on src/pages/add-ons/AddOns.tsx
> +const AddOns = () => {
Mas ini minta tolong dipindah, kemarin udah disiapin untuk komponent add-ons ada di folder pages/booking/component/travel-add/index.tsx

Trus untuk tampilannya ada di /flight/booking

2024-02-02 16:33 UTC, bayuuat approved these changes

2024-02-03 04:18 UTC, Mwazowsky approved these changes

2024-02-03 04:18 UTC, merged