Feat/129/order
SYNRGY-6-TEAM-5/frontend-web pull request #47
Opened 2024-02-01 16:41 UTC by RutriAyut

Layouting untuk halaman Order Active

<img width="948" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/09b8a86d-f3a1-47d4-869e-c94a0328df03">
<img width="955" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/14c39aff-5e9f-4090-8b9f-dd9477b30d6d">

2024-02-01 17:30 UTC, bayuuat requested changes

2024-02-01 17:30 UTC, bayuuat commented on src/pages/profile/pages/my-flight/components/ActiveOrder.tsx
> +                <Text className="text-s font-normal ">You can check-in now</Text>
minta tolong diganti font size ke 14 ya mba, kalo ga salah text-sm

2024-02-01 17:30 UTC, bayuuat commented on src/pages/profile/pages/my-flight/components/ActiveOrder.tsx
> +                <Text className="text-s font-normal ">Time for check in has expired</Text>
ini juga text-sm

2024-02-01 17:30 UTC, bayuuat commented on src/pages/profile/pages/my-flight/components/ActiveOrder.tsx
> +              <Text className="text-s font-normal text-primary-500">Your e-ticket is available!</Text>
ini juga

2024-02-01 17:30 UTC, bayuuat commented on src/pages/profile/pages/my-flight/components/ActiveOrder.tsx
> +        <div key={index} className="space-y-3 p-3 bg-white shadow-3xl h-fit">
ditambahi rounded-lg / rounded-xl biar ada border-radius, disesuaiin aja yg pas

2024-02-01 17:40 UTC, RutriAyut commented on src/pages/profile/pages/my-flight/components/ActiveOrder.tsx
> +                <Text className="text-s font-normal ">You can check-in now</Text>
sudah mas,
bisa minta tolong buat di checkin lagi ?

2024-02-02 04:06 UTC, bayuuat approved these changes

2024-02-02 04:07 UTC, Mwazowsky approved these changes

2024-02-02 04:07 UTC, merged