flight order
SYNRGY-6-TEAM-5/frontend-web pull request #51
Opened 2024-02-05 07:39 UTC by ziyad1412

<img width="643" alt="Capture" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/72376708/d551c915-7dc2-4049-be69-f8ec869071f7">

2024-02-05 07:44 UTC, RutriAyut requested changes

2024-02-05 07:44 UTC, RutriAyut commented on src/pages/profile/pages/order/index.tsx
> +              <img src="/src/assets/order-icon.png" alt="Order Icon" />
untuk image bisa di import dulu seperti ini
<img width="365" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/974d8f05-3e50-4b0e-af65-7f6bcae30428">
kemudian disrc jadi seperti ini
<img width="331" alt="image" src="https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/24217163/5ab2a4e0-915b-4791-9069-12a12665bf46">
kalau seperti in gambarnya tidak tampil
terimakasih

2024-02-05 07:51 UTC, ziyad1412 commented on src/pages/profile/pages/order/index.tsx
> +              <img src="/src/assets/order-icon.png" alt="Order Icon" />
oke baik mbak, terimakasih

2024-02-05 09:23 UTC, bayuuat requested changes
Mas ini yang tab nya sekalian dibuat ya, jangan statis

![image](https://github.com/SYNRGY-6-TEAM-5/frontend-web/assets/68576415/f3c259b8-288f-4e2c-b6d2-10bd962db3c6)

contoh bisa baca disini https://ui.shadcn.com/docs/components/tabs

2024-02-08 04:03 UTC, Mwazowsky approved these changes

2024-02-10 04:33 UTC, merged